### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by Frontier314** [mixtile/loftq-android#1]
Hello,

Following the instructions here: http://mixtile.github.io/en/en-quick-guide.html#android-building

First, android_build_kernel fails with the following error:
<code>
[...]
Image Name:   Linux-3.3.0
Created:      Fri Mar 20 14:02:55 2015
Image Type:   ARM Linux Kernel Image (uncompressed)
Data Size:    4606488 Bytes = 4498.52 kB = 4.39 MB
Load Address: 40008000
Entry Point:  40008000
  Image arch/arm/boot/uImage is ready
'arch/arm/boot/uImage' -> 'output/uImage'
'arch/arm/boot/zImage' -> 'output/zImage'
sun6i compile successful
Building modules
make: Entering directory '/home/manos/work/Mixtile/LoftQ/loftq-linux/modules/eurasia_km/eurasiacon/build/linux2/sunxi_android'
/bin/sh: arm-linux-gnueabi-arm-linux-gnueabi-gcc: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
eurasiacon/build/linux2/tools/cc-check.sh: line 52: ccache: command not found
make[2]: ccache: Command not found
  LD      /home/manos/work/Mixtile/LoftQ/loftq-linux/modules/eurasia_km/eurasiacon/binary2_sunxi_android_release/target/kbuild/built-in.o
/bin/sh: ccache: command not found
scripts/Makefile.build:373: recipe for target '/home/manos/work/Mixtile/LoftQ/loftq-linux/modules/eurasia_km/eurasiacon/binary2_sunxi_android_release/target/kbuild/built-in.o' failed
make[3]: **\* [/home/manos/work/Mixtile/LoftQ/loftq-linux/modules/eurasia_km/eurasiacon/binary2_sunxi_android_release/target/kbuild/built-in.o] Error 127
Makefile:1362: recipe for target '_module_/home/manos/work/Mixtile/LoftQ/loftq-linux/modules/eurasia_km/eurasiacon/binary2_sunxi_android_release/target/kbuild' failed
make[2]: **\* [_module_/home/manos/work/Mixtile/LoftQ/loftq-linux/modules/eurasia_km/eurasiacon/binary2_sunxi_android_release/target/kbuild] Error 2
eurasiacon/build/linux2/kbuild/kbuild.mk:56: recipe for target 'kbuild' failed
make[1]: **\* [kbuild] Error 2
../config/core.mk:671: recipe for target 'build' failed
make: **\* [build] Error 2
make: Leaving directory '/home/manos/work/Mixtile/LoftQ/loftq-linux/modules/eurasia_km/eurasiacon/build/linux2/sunxi_android'
</code>

I've continued with Android build procedure and after command make -j16 (I used -j8 because my CPU does not support many cores), the build fails with error regarding zigbee compilation:

<code>
[...]
target thumb C: loftq-zigbee <= device/softwinner/mars-loftq/loftq-zigbee/src/zb_hl_msg_filter.c
target thumb C: loftq-zigbee <= device/softwinner/mars-loftq/loftq-zigbee/src/zb_hl_power.c
target thumb C: loftq-zigbee <= device/softwinner/mars-loftq/loftq-zigbee/src/zb_ll_fw.c
target thumb C: loftq-zigbee <= device/softwinner/mars-loftq/loftq-zigbee/src/zb_ll_msg.c
In file included from device/softwinner/mars-loftq/loftq-zigbee/src/zb_hl_msg.h:5:0,
                 from device/softwinner/mars-loftq/loftq-zigbee/src/zb_hl_msg.c:1:
device/softwinner/mars-loftq/loftq-zigbee/src/zb_private.h:6:20: fatal error: mqueue.h: No such file or directory
compilation terminated.
make-3.82: target thumb C: loftq-zigbee <= device/softwinner/mars-loftq/loftq-zigbee/src/zb_ll_ops.c
**\* [out/target/product/mars-loftq/obj/EXECUTABLES/loftq-zigbee_intermediates/src/zb_hl_msg.o] Error 1
make-3.82: **\* Waiting for unfinished jobs....
In file included from device/softwinner/mars-loftq/loftq-zigbee/src/zb_hl_msg_filter.h:4:0,
                 from device/softwinner/mars-loftq/loftq-zigbee/src/zb_hl_msg_filter.c:1:
device/softwinner/mars-loftq/loftq-zigbee/src/zb_private.h:6:20: fatal error: mqueue.h: No such file or directory
compilation terminated.
make-3.82: **\* [out/target/product/mars-loftq/obj/EXECUTABLES/loftq-zigbee_intermediates/src/zb_hl_msg_filter.o] Error 1
In file included from device/softwinner/mars-loftq/loftq-zigbee/src/zb_hl_msg.h:5:0,
                 from device/softwinner/mars-loftq/loftq-zigbee/src/zb_hl_power.c:6:
device/softwinner/mars-loftq/loftq-zigbee/src/zb_private.h:6:20: fatal error: mqueue.h: No such file or directory
compilation terminated.
make-3.82: **\* [out/target/product/mars-loftq/obj/EXECUTABLES/loftq-zigbee_intermediates/src/zb_hl_power.o] Error 1
[...]
</code>

Tried updating the downloaded android source (in hope for a fix) using git pull but no access is possible.

Thank you very much in advance.

**Comment by pengphei** [comment]
issue reply:
1. kernel building error.
   
   it seems that you need to install `ccache`, for ubuntu, you will need to run cmd as below:
   
   ``` bash
   sudo apt-get install ccache
   ```
2. Android building problem
   
   I am sorry that I added the broken package `loftq-zigbee` to the Andriod source, which is the package for our zigbee chip. it needs **posix mqueue** support, but Android doesn't provide this feature and referring library.
   
   fixed method: just remove `loftq-zigbee` directory from `android/device/softwinner/mars-loftq`.

**Comment by Frontier314** [comment]
Regarding zigbee - which LoftQ provides - do you plan to provide an Android compilable source package or we have to use a precompiled binary?

Thank you very much for your help and support.

**Comment by pengphei** [comment]
I better hope to provide the compliable source package, so the message system needs to be restructured, and it will need some time.

**Comment by Frontier314** [comment]
Thank you very much for your help.
